FROM ubuntu:22.04

RUN mkdir /opt/cruster \
    && useradd -u 4242 --shell /bin/bash --home /opt/cruster cruster \
    && chown -R cruster /opt/cruster \
    && chmod u+rwx /opt/cruster

# For ncurses
RUN apt-get update \
    && apt-get install --no-install-recommends -y \
        locales=2.35-0ubuntu3.1 \
    && locale-gen en_US.UTF-8

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
ENV NCURSES_NO_UTF8_ACS=1

RUN apt-get install --no-install-recommends -y \
        build-essential \
        pkg-config \
        curl \
        git \
        ca-certificates \
        libssl-dev \
        libncursesw5-dev \
        openssl \
        ncurses-base \
        ncurses-bin \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/cruster

USER cruster

ENV PATH="/opt/cruster/.cargo/bin:$PATH"

RUN curl --proto '=https' --tlsv1.2 -sSf -o rustup.sh https://sh.rustup.rs \
    && sh rustup.sh -y \
    && mkdir cruster-src

COPY src cruster-src/src
COPY Cargo.toml cruster-src/
COPY Cargo.lock cruster-src/

RUN cargo install \
    --path ./cruster-src \
    --no-default-features \
    --features openssl-ca,ncurses

ENTRYPOINT [ "cruster" ]
